services:
  webserver:
    container_name: gpt_webserver
    build:
     context: ./WebServer
     dockerfile: Dockerfile
    environment:
      - WATCHPACK_POLLING=true
    ports:
     - "3000:3000"
    depends_on:
      - database
    volumes:
     - ./WebServer/pages:/app/pages
     - ./WebServer/db:/app/db
    networks:
      - test_net
  database:
    container_name: redis
    build:
      context: ./Database
      dockerfile: Dockerfile
    restart: always
    ports:
     - "6379:6379"
    volumes:
     - redis_data:/data
    networks:
      - test_net
volumes:
  redis_data:
networks:
  test_net: