services:
  webserver:
    build: "WebServer"
    ports:
     - "3000:3000"
    depends_on:
      - database
  database:
    image: redis
    ports:
     - "6379:6379"
    volumes:
     - redis_data:/Database/db_data
volumes:
  redis_data: